/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunoRouteImport } from './routes/aluno'
import { Route as AdminAlunosRouteImport } from './routes/admin.alunos'
import { Route as AdminCheckinRouteImport } from './routes/admin.checkin'
import { Route as AdminTreinosRouteImport } from './routes/admin.treinos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunoRoute = AlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlunosRoute = AdminAlunosRouteImport.update({
  id: '/admin/alunos',
  path: '/admin/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinRoute = AdminCheckinRouteImport.update({
  id: '/admin/checkin',
  path: '/admin/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTreinosRoute = AdminTreinosRouteImport.update({
  id: '/admin/treinos',
  path: '/admin/treinos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/treinos': typeof AdminTreinosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/treinos': typeof AdminTreinosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aluno': typeof AlunoRoute
  '/admin/alunos': typeof AdminAlunosRoute
  '/admin/checkin': typeof AdminCheckinRoute
  '/admin/treinos': typeof AdminTreinosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/aluno' | '/admin/alunos' | '/admin/checkin' | '/admin/treinos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aluno' | '/admin/alunos' | '/admin/checkin' | '/admin/treinos'
  id:
    | '__root__'
    | '/'
    | '/aluno'
    | '/admin/alunos'
    | '/admin/checkin'
    | '/admin/treinos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunoRoute: typeof AlunoRoute
  AdminAlunosRoute: typeof AdminAlunosRoute
  AdminCheckinRoute: typeof AdminCheckinRoute
  AdminTreinosRoute: typeof AdminTreinosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aluno': {
      id: '/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AlunoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alunos': {
      id: '/admin/alunos'
      path: '/admin/alunos'
      fullPath: '/admin/alunos'
      preLoaderRoute: typeof AdminAlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin': {
      id: '/admin/checkin'
      path: '/admin/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treinos': {
      id: '/admin/treinos'
      path: '/admin/treinos'
      fullPath: '/admin/treinos'
      preLoaderRoute: typeof AdminTreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunoRoute: AlunoRoute,
  AdminAlunosRoute: AdminAlunosRoute,
  AdminCheckinRoute: AdminCheckinRoute,
  AdminTreinosRoute: AdminTreinosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
